use_frameworks!

platform :ios, '10.0'

target 'Example' do
  pod 'GKScrollView', :path => '../'
  
  pod 'RxSwift'
  pod 'Alamofire'
  pod 'HandyJSON'
  pod 'Kingfisher'
  pod 'MJRefresh'
  pod 'GKNavigationBarSwift'
  pod 'SnapKit'
  
  pod 'ZFPlayer/AVPlayer'
  pod 'SJVideoPlayer'
  pod 'GKSlider'
  
end

post_install do |installer|
  # 消除版本警告
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 12.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
  end
  
  installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      end
  end
end
