use_frameworks!

platform :ios, '10.0'

target 'Example' do
  pod 'GKScrollView', :path => '../'
  
  pod 'RxSwift'
  pod 'Alamofire'
  pod 'HandyJSON'
  pod 'Kingfisher'
  pod 'MJRefresh'
  pod 'GKNavigationBarSwift'
  pod 'SnapKit'
  
  pod 'ZFPlayer/AVPlayer'
  pod 'SJVideoPlayer'
  pod 'GKSlider'
  
end

post_install do |installer|
  # 消除版本警告
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 12.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
  end
  
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # 处理 M1 芯片上不支持 模拟器 运行问题：不仅仅编译活跃的架构，反之就是 i386、x86_64、arm64 等架构都编译。
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
    end
  end
end
