use_frameworks!

platform :ios, '13.0'

target 'Demo' do

  pod 'GKScrollView', :path => '../'
  
  pod 'RxSwift'
  pod 'Alamofire'
  pod 'HandyJSON'
  pod 'Kingfisher'
  pod 'MJRefresh'
  pod 'GKNavigationBarSwift'
  pod 'SnapKit'
  pod 'Booming'
  pod 'RxNetworks/HandyJSON'
  pod 'RxNetworks/RxSwift'
  pod 'NSObject+Rx'
  
  pod 'ZFPlayer/AVPlayer'
  pod 'SJVideoPlayer'
  pod 'GKSlider'

  pod 'GKPopupController'
  
end

post_install do |installer|
  # 消除版本警告
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 13.0
        config.build_settings['IPHONES_DEPLOYMENT_TARGET'] = '13.0'
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      end
    end
  end
end
